# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['@all']
  'require':
    'frameworks/extra-cmake-modules': '@stable'
    'frameworks/kbookmarks': '@stable'
    'frameworks/kcompletion': '@stable'
    'frameworks/kiconthemes': '@stable'
    'frameworks/kitemviews': '@stable'
    'frameworks/kio': '@stable'
    'frameworks/knewstuff': '@stable'
    'frameworks/kparts': '@stable'
    'frameworks/kservice': '@stable'
    'frameworks/kwidgetsaddons': '@stable'
    'frameworks/kxmlgui': '@stable'
    'frameworks/kcrash': '@stable'
    'frameworks/kdbusaddons': '@stable'
    'frameworks/kdoctools': '@stable'
    'frameworks/kconfigwidgets': '@stable'
    'frameworks/ki18n': '@stable'

Options:
  require-passing-tests-on: [ 'Linux', 'FreeBSD' ]
